# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
