# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashcan', '0002_trashcan_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(help_text='Distancia del sensor a la basura (en centimetros)')),
                ('trash_can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='trashcan.TrashCan')),
            ],
            options={
                'db_table': 'level',
            },
        ),
    ]
